version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: fincas_postgres

    restart: always

    environment:
      POSTGRES_DB: fincas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend

    container_name: fincas_backend

    restart: always

    ports:
      - "3000:3000"

    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: fincas_db
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      - postgres

  frontend-admin:
    build:
      context: ./frontend-admin
    container_name: fincas_frontend_admin
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://backend:3000
    depends_on:
      - backend

volumes:
  postgres_data: